FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD Shtefan.jar /opt/Shtefan/
EXPOSE 8080
WORKDIR /opt/Shtefan/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "Shtefan.jar"]
